# Site settings
title: Material Jekyll
email: hello@joshuaraichur.com
description: A Material Design inspired Jekyll theme
baseurl: ""
url: "http://joshuaraichur.com/material-jekyll"

# Social usernames
twitter_username: JoshuaRaichur
github_username:  raichur

# Build settings
markdown: kramdown
include: ['_pages', '_assets']
sass:
  sass_dir: '_assets/_sass'
